#!/bin/bash

echo "================================"
echo "  
Food-Delivery-Website - Git Setup"
echo "================================"

# Initialize git if not already
if [ ! -d ".git" ]; then
  echo "Initializing git repository..."
  git init
else
  echo "Git already initialized."
fi

# Create root .gitignore
echo "Creating root .gitignore..."
cat > .gitignore << 'EOF'
# Environment files - NEVER commit these
.env
.env.local
.env.development
.env.production
.env.test

# Dependencies
node_modules/
*/node_modules/

# Logs
logs/
*.log
npm-debug.log*

# OS files
.DS_Store
Thumbs.db

# Build output
dist/
build/

# Excel downloads generated by app
*.xlsx

# VS Code
.vscode/
EOF

# Create backend .gitignore
echo "Creating backend/.gitignore..."
cat > backend/.gitignore << 'EOF'
.env
node_modules/
*.xlsx
*.log
EOF

# Create frontend .gitignore (if folder exists)
if [ -d "frontend" ]; then
  echo "Creating frontend/.gitignore..."
  cat > frontend/.gitignore << 'EOF'
.env
.env.local
node_modules/
dist/
build/
EOF
fi

# Create .env.example for backend so others know what vars are needed
if [ -f "backend/.env" ]; then
  echo "Creating backend/.env.example..."
  grep -oP '^[A-Z_]+(?==)' backend/.env | while read key; do
    echo "$key=your_value_here"
  done > backend/.env.example
  echo "backend/.env.example created from your existing .env keys."
fi

# Set remote origin
echo "Setting remote origin..."
git remote remove origin 2>/dev/null
git remote add origin https://github.com/rdgtech-ctrl/Food-Delivery-Website.git
echo ""
echo "✅ Setup complete!"
echo "   - .gitignore files created (.env and node_modules are protected)"
echo "   - Remote origin set to: https://github.com/rdgtech-ctrl/Food-Delivery-Website.git"
echo ""
echo "Now run: bash push.sh"